local addonName, ns = ...

-- Default configuration values
ns.Config = {
    -- Media settings (textures, fonts)
    Media = {
        HealthBar = "oUF_MyLayout Gradient",
        PowerBar = "oUF_MyLayout Minimalist",
        Font = "oUF_MyLayout Prototype",
    },
    
    -- Color settings
    Colors = {
        Health = {0.25, 0.25, 0.25},
        HealthBg = {0, 0, 0},
        Power = {0.25, 0.25, 0.25},
        PowerBg = {0, 0, 0},
        Castbar = {1, 0.7, 0},
        CastbarBg = {0.2, 0.2, 0.2},
    },

    -- Unit specific settings (size, position, etc.)
    Units = {
        Player = {
            Enable = true,
            Width = 254,
            Height = 46,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = true,
            HealthTag = "[my:perhp]%",
            NameTag = "[raidcolor][name]",
            NameText = {
                Font = nil, -- Use Media.Font if nil
                Size = 20,
                Outline = "OUTLINE",
                Point = "LEFT",
                Y = -40,
                Enable = false
            },
            HealthText = {
                Font = nil,
                Size = 24,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = -8,
                Y = -3,
            },
            Castbar = {
                Enable = true,
                Point = "TOPLEFT",
                RelativeTo = "FRAME",
                RelativePoint = "BOTTOMLEFT",
                X = 0,
                Y = -30,
                Width = 0, -- 0 for auto
                Height = 20,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = true,
                Width = 150,
                Height = 42,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 42, Point = "TOP", X = 0, Y = 25 },
                GroupRole = { Enable = true, Size = 32, Point = "TOPRIGHT", X = 15, Y = 15 },
                ReadyCheck = { Enable = true, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Resting = { Enable = true, Size = 32, Point = "TOPLEFT", X = -10, Y = 10 },
                Combat = { Enable = true, Size = 32, Point = "BOTTOMLEFT", X = -10, Y = -10 },
                Leader = { Enable = true, Size = 32, Point = "TOPLEFT", X = -15, Y = 15 },
                Assistant = { Enable = true, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"CENTER", -200, -200},
        },
        Target = {
            Enable = true,
            Width = 254,
            Height = 46,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = true,
            HealthTag = "[my:perhp]%",
            NameTag = "[level] [raidcolor][name]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
                Point = "LEFT",
                Y = -40,
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = -8,
                Y = -3,
            },
            Castbar = {
                Enable = true,
                Point = "TOPLEFT",
                RelativeTo = "FRAME",
                RelativePoint = "BOTTOMLEFT",
                X = 0,
                Y = -30,
                Width = 0, -- 0 for auto
                Height = 20,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = true,
                Width = 150,
                Height = 42,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 42, Point = "TOP", X = 0, Y = 25 },
                GroupRole = { Enable = true, Size = 32, Point = "TOPRIGHT", X = 15, Y = 15 },
                ReadyCheck = { Enable = true, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = true, Size = 32, Point = "TOPLEFT", X = -15, Y = 15 },
                Assistant = { Enable = true, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = true,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = true,
            },
            Position = {"CENTER", 200, -200},
        },
        TargetTarget = {
            Enable = true,
            Width = 134,
            Height = 26,
            HealthHeight = 10,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = false,
            HealthTag = "",
            ShortNameLength = 10,
            NameTag = "[raidcolor][my:shortname]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
                Point = "CENTER",
                Y = -5,
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = -8,
                Y = -3,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 42, Point = "TOP", X = 0, Y = 25 },
                GroupRole = { Enable = false, Size = 32, Point = "TOPRIGHT", X = 15, Y = 15 },
                ReadyCheck = { Enable = false, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = false, Size = 32, Point = "TOPLEFT", X = -15, Y = 15 },
                Assistant = { Enable = false, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Position = {"CENTER", 400, -210},
        },
        Focus = {
            Enable = true,
            Width = 134,
            Height = 26,
            HealthHeight = 10,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = false,
            HealthTag = "",
            ShortNameLength = 10,
            NameTag = "[raidcolor][my:shortname]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
                Point = "CENTER",
                Y = -5,
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = -8,
                Y = -3,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 42, Point = "TOP", X = 0, Y = 25 },
                GroupRole = { Enable = false, Size = 32, Point = "TOPRIGHT", X = 15, Y = 15 },
                ReadyCheck = { Enable = false, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = false, Size = 32, Point = "TOPLEFT", X = -15, Y = 15 },
                Assistant = { Enable = false, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Position = {"CENTER", -400, -210},
        },
        Pet = {
            Enable = true,
            Width = 134,
            Height = 46,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "",
            NameTag = "[raidcolor][name]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
                Point = "BOTTOM",
                Y = -25,
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = 0,
                Y = 0,
            },
            Castbar = {
                Enable = true,
                Point = "TOPLEFT",
                RelativeTo = "FRAME",
                RelativePoint = "BOTTOMLEFT",
                X = 0,
                Y = -5,
                Width = 0, -- 0 for auto
                Height = 20,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = false,
                Width = 78,
                Height = 42,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 36, Point = "TOP", X = 0, Y = 10 },
                GroupRole = { Enable = false, Size = 32, Point = "TOPRIGHT", X = 10, Y = 10 },
                ReadyCheck = { Enable = false, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = false, Size = 32, Point = "TOPLEFT", X = -10, Y = 10 },
                Assistant = { Enable = false, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"CENTER", 0, -200},
        },
        Party = {
            Enable = true,
            Width = 184,
            Height = 46,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = true,
            HealthTag = "[my:perhp]%",
            NameTag = "[level] [raidcolor][name]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
                Point = "LEFT",
                Y = -40
            },
            HealthText = {
                Size = 20,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = -8,
                Y = -3,
            },
            Castbar = {
                Enable = true,
                Point = "TOPLEFT",
                RelativeTo = "FRAME",
                RelativePoint = "BOTTOMLEFT",
                X = 0,
                Y = -25,
                Width = 0, -- 0 for auto
                Height = 20,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = true,
                Width = 108,
                Height = 42,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 32, Point = "TOP", X = 0, Y = 15 },
                GroupRole = { Enable = true, Size = 32, Point = "TOPRIGHT", X = 15, Y = 15 },
                ReadyCheck = { Enable = true, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = true, Size = 32, Point = "TOPLEFT", X = -15, Y = 15 },
                Assistant = { Enable = true, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"LEFT", 200, 150},
        },
        PartyTarget = {
            Enable = true,
            Width = 140,
            Height = 46,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = false,
            HealthTag = "",
            ShortNameLength = 10,
            NameTag = "[raidcolor][my:shortname]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
                Point = "CENTER",
                Y = -8
            },
            HealthText = {
                Size = 12,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = 0,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 32, Point = "TOP", X = 0, Y = 15 },
            },
            Buffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 5,
                PlayerOnly = false,
            },
            Position = {"LEFT", 400, 150},
        },
        Raid = {
            Enable = true,
            ShowSolo = true,
            ShowParty = true,
            Width = 80,
            Height = 36,
            HealthHeight = 22,
            PowerHeight = 8,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "",
            ShortNameLength = 10,
            ShowStatusText = true,
            NameTag = "[raidcolor][my:shortname]",
            NameText = {
                Size = 12,
                Outline = "OUTLINE",
                Point = "CENTER",
                Y = -4,
            },
            HealthText = {
                Size = 16,
                Outline = "OUTLINE",
                Point = "CENTER",
                X = 0,
                Y = -15,
            },
            Portrait = {
                Enable = false,
                Width = 48,
                Height = 35,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 20, Point = "TOP", X = 0, Y = 10 },
                GroupRole = { Enable = true, Size = 20, Point = "TOPRIGHT", X = 5, Y = 5 },
                ReadyCheck = { Enable = true, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = true, Size = 20, Point = "TOPLEFT", X = -5, Y = 5 },
                Assistant = { Enable = true, Size = 20, Point = "TOPLEFT", X = -5, Y = 5 },
            },
            Buffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 5,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 20,
                PlayerOnly = false,
            },
            Position = {"TOPLEFT", "UIParent", "BOTTOMRIGHT", -430, 225 },
        },
        Boss = {
            Enable = true,
            Width = 160,
            Height = 40,
            HealthHeight = 26,
            PowerHeight = 8,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = true,
            HealthTag = "[my:perhp]%",
            ShortNameLength = 10,
            NameTag = "[raidcolor][my:shortname]",
            NameText = {
                Size = 16,
                Outline = "OUTLINE",
                Point = "LEFT",
                X = 5
            },
            HealthText = {
                Size = 16,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = 0,
                Y = 0,
            },
            Portrait = {
                Enable = false,
                Width = 96,
                Height = 40,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 20, Point = "TOP", X = 0, Y = 0 },
                GroupRole = { Enable = false, Size = 32, Point = "TOPRIGHT", X = 10, Y = 10 },
                ReadyCheck = { Enable = false, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = false, Size = 32, Point = "TOPLEFT", X = -10, Y = 10 },
                Assistant = { Enable = false, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"TOPRIGHT", "UIParent", "TOPRIGHT", -10, -250},
        },
        MainTank = {
            Enable = true,
            Width = 120,
            Height = 38,
            HealthHeight = 24,
            PowerHeight = 8,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = true,
            HealthTag = "[my:perhp]%",
            ShortNameLength = 10,
            NameTag = "[raidcolor][my:shortname]",
            NameText = {
                Size = 16,
                Outline = "OUTLINE",
                Point = "LEFT",
                X = 5
            },
            HealthText = {
                Size = 16,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = -5,
                Y = 0,
            },
            Portrait = {
                Enable = false,
                Width = 72,
                Height = 35,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 20, Point = "TOP", X = 0, Y = 0 },
                GroupRole = { Enable = true, Size = 20, Point = "TOPRIGHT", X = 10, Y = 10 },
                ReadyCheck = { Enable = true, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = true, Size = 20, Point = "TOPLEFT", X = -10, Y = 10 },
                Assistant = { Enable = true, Size = 20, Point = "TOPLEFT", X = -10, Y = 10 },
            },
            Buffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 5,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 20,
                PlayerOnly = false,
            },
            Position = {"TOPRIGHT", "UIParent", "BOTTOMRIGHT", -10, 320 },
        },
        MainTankTarget = {
            Enable = true,
            Width = 120,
            Height = 38,
            HealthHeight = 24,
            PowerHeight = 8,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = true,
            HealthTag = "",
            ShortNameLength = 10,
            NameTag = "[raidcolor][my:shortname]",
            NameText = {
                Size = 14,
                Outline = "OUTLINE",
                Point = "LEFT",
                X = 5
            },
            HealthText = {
                Size = 14,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = -5,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = true, Size = 20, Point = "TOP", X = 0, Y = 0 },
            },
            Buffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 5,
                PlayerOnly = false,
            },
            Position = {"TOPRIGHT", "UIParent", "BOTTOMRIGHT", -140, 320 },
        },
        -- Default (other than above)
        Default = {
            Enable = true,
            Width = 254,
            Height = 47,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HideHealthTextAtFull = true,
            ShowStatusText = true,
            HealthTag = "[my:perhp]%",
            NameTag = "[raidcolor][name]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
                Point = "RIGHT",
                X = 0,
                Y = 0,
            },
            Castbar = {
                Enable = true,
                Point = "TOPLEFT",
                RelativeTo = "FRAME",
                RelativePoint = "BOTTOMLEFT",
                X = 0,
                Y = -5,
                Width = 0, -- 0 for auto
                Height = 20,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = false,
                Width = 150,
                Height = 43,
                X = 2,
                Y = 0,
            },
            Icons = {
                RaidTarget = { Enable = false, Size = 20, Point = "TOP", X = 0, Y = 0 },
                GroupRole = { Enable = false, Size = 32, Point = "TOPRIGHT", X = 10, Y = 10 },
                ReadyCheck = { Enable = false, Size = 24, Point = "CENTER", X = 0, Y = 0 },
                Leader = { Enable = false, Size = 32, Point = "TOPLEFT", X = -10, Y = 10 },
                Assistant = { Enable = false, Size = 16, Point = "TOPLEFT", X = 2, Y = -2 },
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
        }
    },
}