local addonName, ns = ...

-- 設定のデフォルト値
ns.Config = {
    -- メディア設定 (テクスチャ、フォント)
    Media = {
        HealthBar = "oUF_MyLayout Gradient",
        PowerBar = "oUF_MyLayout Minimalist",
        Font = "oUF_MyLayout Prototype",
    },
    
    -- 色設定
    Colors = {
        Health = {0.25, 0.25, 0.25},
        HealthBg = {0, 0, 0},
        PowerBg = {1, 1, 1},
        Castbar = {1, 0.7, 0},
        CastbarBg = {0.2, 0.2, 0.2},
    },

    -- ユニットごとの設定 (サイズ、位置など)
    Units = {
        Player = {
            Enable = true,
            Width = 254,
            Height = 47,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "[perhp]%",
            NameText = {
                Font = nil, -- nilの場合はMedia.Fontを使用
                Size = 20,
                Outline = "OUTLINE",
            },
            HealthText = {
                Font = nil,
                Size = 24,
                Outline = "OUTLINE",
            },
            Castbar = {
                Enable = true,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = true,
                Width = 150,
                Height = 43,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"CENTER", -200, -200},
        },
        Target = {
            Enable = true,
            Width = 254,
            Height = 47,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "[perhp]%",
            NameTag = "[raidcolor][name] [dead][offline][my:afk]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
            },
            Castbar = {
                Enable = true,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = true,
                Width = 150,
                Height = 43,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = true,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = true,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"CENTER", 200, -200},
        },
        Pet = {
            Enable = true,
            Width = 134,
            Height = 47,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            NameTag = "[name] [dead][offline]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
            },
            Castbar = {
                Enable = true,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = false,
                Width = 78,
                Height = 43,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"CENTER", 0, -200},
        },
        Party = {
            Enable = true,
            Width = 184,
            Height = 44,
            HealthHeight = 25,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "[perhp]%",
            NameTag = "[name] [dead][offline]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            Castbar = {
                Enable = true,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = true,
                Width = 108,
                Height = 40,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"TOPLEFT", 150, -200},
        },
        Raid = {
            Enable = true,
            Width = 80,
            Height = 35,
            HealthHeight = 22,
            PowerHeight = 8,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "[perhp]%",
            NameTag = "[raidcolor][name]",
            NameText = {
                Size = 12,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = false,
                Width = 48,
                Height = 35,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 5,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 20,
                PlayerOnly = false,
            },
            Position = {"TOPLEFT", "UIParent", "BOTTOMRIGHT", -435, 225},
        },
        Boss = {
            Enable = true,
            Width = 160,
            Height = 40,
            HealthHeight = 26,
            PowerHeight = 8,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "[perhp]%",
            NameTag = "[raidcolor][name] [dead][offline]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = false,
                Width = 96,
                Height = 40,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
            Position = {"TOPRIGHT", "UIParent", "TOPRIGHT", 5, -300},
        },
        MainTank = {
            Enable = true,
            Width = 120,
            Height = 35,
            HealthHeight = 26,
            PowerHeight = 8,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "[perhp]%",
            NameTag = "[raidcolor][name]",
            NameText = {
                Size = 12,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = false,
                Width = 72,
                Height = 35,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 5,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 12,
                X = 0,
                Y = 20,
                PlayerOnly = false,
            },
            Position = {"TOPLEFT", 50, -350},
        },
        -- デフォルト (上記以外)
        Default = {
            Enable = true,
            Width = 254,
            Height = 47,
            HealthHeight = 30,
            PowerHeight = 10,
            PowerBarTexture = nil,
            HealthBarTexture = nil,
            HealthTag = "[perhp]%",
            NameTag = "[raidcolor][name] [dead][offline][my:afk]",
            NameText = {
                Size = 20,
                Outline = "OUTLINE",
            },
            HealthText = {
                Size = 24,
                Outline = "OUTLINE",
            },
            Castbar = {
                Enable = true,
            },
            CastbarText = {
                Font = nil,
                Size = 12,
                Outline = "OUTLINE",
            },
            Portrait = {
                Enable = false,
                Width = 150,
                Height = 43,
                X = 2,
                Y = 0,
            },
            Buffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 10,
                PlayerOnly = false,
            },
            Debuffs = {
                Enable = false,
                Size = 20,
                X = 0,
                Y = 35,
                PlayerOnly = false,
            },
        }
    },
}